kind: Deployment
apiVersion: apps/v1
metadata:
  name: kafka-to-es
  namespace: kafka-er
  labels:
    app: kafka-to-es
    app.kubernetes.io/component: kafka-to-es
    app.kubernetes.io/instance: kafka-to-es
    app.kubernetes.io/part-of: kafka-to-es-app
    app.openshift.io/runtime-namespace: kafka-er
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-to-es
  template:
    metadata:
      labels:
        app: kafka-to-es
        deploymentconfig: kafka-to-es
    spec:
      imagePullSecrets:
      - name: registry.rd.ertelecom.ru
      containers:
        - resources:
            limits:
              cpu: '1'
              memory: 1Gi
          name: kafka-to-es
          image: registry.rd.ertelecom.ru/tvbe/kafka-to-es:master
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
          - name: KAFKA_HOST
            value: kafka-svc.prod:9092
          - name: KAFKA_TOPIC
            value: er-log
          - name: USE_SIMPLE_DECODER
            value: "1"
      restartPolicy: Always
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-to-es-svc
spec:
  selector:
    app: kafka-to-es
  ports:
  - protocol: "TCP"
    port: 8080
  type: LoadBalancer
